name: "Create new version and pre release"

on:
  push:
    branches:
      - main

jobs:
  version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and pre-release
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GH_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          changelog_increment_filename: "release-notes.md"
      - name: Prepare Draft Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "release-notes.md"
          tag_name: v${{ steps.cz.outputs.version }}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
